/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_grafica;

/**
 *
 * @author Miguel
 */
public class interfaz_crear_soldado extends javax.swing.JFrame {

    /**
     * Creates new form interfaz_crear_soldado
     */
    public interfaz_crear_soldado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel_menu = new javax.swing.JPanel();
        panel_de_campo_de_nombre = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Entrada_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        boton_crear = new javax.swing.JButton();
        boton_volver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Capitan_radioButton = new javax.swing.JRadioButton();
        SoldadoRaso_radioButton = new javax.swing.JRadioButton();
        Coronel_radioButton = new javax.swing.JRadioButton();
        Teniente_radioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 51));

        panel_menu.setBackground(new java.awt.Color(0, 102, 51));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_de_campo_de_nombre.setBackground(new java.awt.Color(0, 102, 51));
        panel_de_campo_de_nombre.setLayout(new java.awt.GridLayout(0, 1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("nombre");
        panel_de_campo_de_nombre.add(jLabel4);

        Entrada_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_nombreActionPerformed(evt);
            }
        });
        panel_de_campo_de_nombre.add(Entrada_nombre);

        panel_menu.add(panel_de_campo_de_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 290, 110));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear soldado");
        panel_menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, -1));

        boton_crear.setText("crear");
        boton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crearActionPerformed(evt);
            }
        });
        panel_menu.add(boton_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        boton_volver.setText("volver");
        boton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverActionPerformed(evt);
            }
        });
        panel_menu.add(boton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("rango");
        panel_menu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 127, -1));

        buttonGroup1.add(Capitan_radioButton);
        Capitan_radioButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Capitan_radioButton.setForeground(new java.awt.Color(255, 255, 255));
        Capitan_radioButton.setText("Capitan");
        panel_menu.add(Capitan_radioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 130, 37));

        buttonGroup1.add(SoldadoRaso_radioButton);
        SoldadoRaso_radioButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        SoldadoRaso_radioButton.setForeground(new java.awt.Color(255, 255, 255));
        SoldadoRaso_radioButton.setText("SoldadoRaso");
        SoldadoRaso_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoldadoRaso_radioButtonActionPerformed(evt);
            }
        });
        panel_menu.add(SoldadoRaso_radioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 130, 37));

        buttonGroup1.add(Coronel_radioButton);
        Coronel_radioButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Coronel_radioButton.setForeground(new java.awt.Color(255, 255, 255));
        Coronel_radioButton.setText("Coronel");
        Coronel_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Coronel_radioButtonActionPerformed(evt);
            }
        });
        panel_menu.add(Coronel_radioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 130, 37));

        buttonGroup1.add(Teniente_radioButton);
        Teniente_radioButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Teniente_radioButton.setForeground(new java.awt.Color(255, 255, 255));
        Teniente_radioButton.setText("Teniente");
        panel_menu.add(Teniente_radioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 130, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_crearActionPerformed

    private void boton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverActionPerformed
         this.dispose();
    }//GEN-LAST:event_boton_volverActionPerformed

    private void Entrada_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_nombreActionPerformed

    private void SoldadoRaso_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoldadoRaso_radioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoldadoRaso_radioButtonActionPerformed

    private void Coronel_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Coronel_radioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Coronel_radioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_crear_soldado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_crear_soldado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_crear_soldado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_crear_soldado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_crear_soldado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Capitan_radioButton;
    private javax.swing.JRadioButton Coronel_radioButton;
    private javax.swing.JTextField Entrada_nombre;
    private javax.swing.JRadioButton SoldadoRaso_radioButton;
    private javax.swing.JRadioButton Teniente_radioButton;
    private javax.swing.JButton boton_crear;
    private javax.swing.JButton boton_volver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panel_de_campo_de_nombre;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
