package controlador;

public enum Operacion {
    CREAR_SOLDADO, MODIFICAR_SOLDADO, MOSTRAR_INFORMACION, ASIGNAR_MISION, REALIZAR_ACCION, 
    REPORTAR_ESTADO, PATRULLAR, SALUDAR, REGAÑAR, RESETEAR, OBTENER_CANTIDADES
}
