package Militar.misiones;

public enum Misiones {
    //zona de misiones
    PATRULLAR_PERIMETRO,
    ASISTIR_LOGISTICA,
    MANTENIMIENTO_EQUIPO,
    SUPERVISAR_TROPAS,
    PLANIFICAR_TACTICAS,
    REPORTAR_ACTIVIDAD,
    COMANDAR_TROPAS,
    ESTRATEGIAS_OFENSIVAS,
    NEGOCIAR_CONFLICTOS,
    PLANIFICAR_ESTRATEGIAS,
    REPRESENTAR_MILITAR,
    COORDINAR_BATALLONES
}
