/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.interfaz_grafica;

import java.util.ArrayList;

import Militar.Soldados.Soldado;

/**
 *
 * @author Miguel
 */
public class Modificar_soldado_raso_teniente extends javax.swing.JFrame {
    public static ArrayList<Soldado> listaSoldados = new ArrayList<>(); 
    public interfaz_principal interfaz;
    /**
     * Creates new form Modificar_soldado
     */
    public Modificar_soldado_raso_teniente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Boton_guardar_cambios = new javax.swing.JButton();
        Boton_volver = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Boton_subir_rango = new javax.swing.JButton();
        Boton_bajar_rango = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        entrada_nombre = new javax.swing.JTextField();
        entrada_unidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_menu.setBackground(new java.awt.Color(0, 102, 51));
        Panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modificar soldado");
        Panel_menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, -1));

        Boton_guardar_cambios.setText("guardar cambios");
        Boton_guardar_cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_guardar_cambiosActionPerformed(evt);
            }
        });
        Panel_menu.add(Boton_guardar_cambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 273, -1, 30));

        Boton_volver.setText("volver");
        Boton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_volverActionPerformed(evt);
            }
        });
        Panel_menu.add(Boton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 273, -1, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("para soldados raso y teniente");
        Panel_menu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 260, 110));

        Boton_subir_rango.setText("subir");
        Boton_subir_rango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_subir_rangoActionPerformed(evt);
            }
        });
        Panel_menu.add(Boton_subir_rango, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 102, 43));

        Boton_bajar_rango.setText("bajar");
        Boton_bajar_rango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_bajar_rangoActionPerformed(evt);
            }
        });
        Panel_menu.add(Boton_bajar_rango, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 102, 43));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rango");
        Panel_menu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 205, 43));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("unidad");
        Panel_menu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 205, 43));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("nombre");
        Panel_menu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 205, 43));

        entrada_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrada_nombreActionPerformed(evt);
            }
        });
        Panel_menu.add(entrada_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 205, 43));

        entrada_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrada_unidadActionPerformed(evt);
            }
        });
        Panel_menu.add(entrada_unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 205, 43));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_guardar_cambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_guardar_cambiosActionPerformed
        /*codigo aqui */
    }//GEN-LAST:event_Boton_guardar_cambiosActionPerformed

    private void Boton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_volverActionPerformed
        this.dispose();
    }//GEN-LAST:event_Boton_volverActionPerformed

    private void entrada_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrada_nombreActionPerformed
        /*codigo aqui */
    }//GEN-LAST:event_entrada_nombreActionPerformed

    private void entrada_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrada_unidadActionPerformed
        /*codigo aqui */
    }//GEN-LAST:event_entrada_unidadActionPerformed

    private void Boton_bajar_rangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_bajar_rangoActionPerformed
        this.dispose();
    }//GEN-LAST:event_Boton_bajar_rangoActionPerformed

    private void Boton_subir_rangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_subir_rangoActionPerformed
        /*codigo aqui */
    }//GEN-LAST:event_Boton_subir_rangoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_soldado_raso_teniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_soldado_raso_teniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_soldado_raso_teniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_soldado_raso_teniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_soldado_raso_teniente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_bajar_rango;
    private javax.swing.JButton Boton_guardar_cambios;
    private javax.swing.JButton Boton_subir_rango;
    private javax.swing.JButton Boton_volver;
    private javax.swing.JPanel Panel_menu;
    private javax.swing.JTextField entrada_nombre;
    private javax.swing.JTextField entrada_unidad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
